

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  check-remote-site:
    runs-on: ubuntu-latest
    steps:
      - uses: peterekepeter/test-with-browser@main
        timeout-minutes: 1
        with:
          url: 'https://github.com/status'
  test-filesystem-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peterekepeter/test-with-browser@main
        timeout-minutes: 1
        with:
          url: 'file://${{ github.workspace }}/test/static-site/index.html'
